openapi: 3.0.3
# Todo パラメータとレスポンス（エラー含め）の詳細を書く

info:
  title: Nyapu API
  version: 1.0.0

paths:
  /api-auth/login/:
    post:
      summary: JWTトークンを取得
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: ""

  /api-auth/token/refresh/:
    post:
      summary: JWTトークンを再取得
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: ""

  /api-auth/token/verify/:
    post:
      summary: JWTトークンを検証
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: ""

  /api/diaries/:
    get:
      summary: 日記の一覧を取得
      parameters:
        - in: query
          name: query
          description: 文字列にタイトル or 本文が部分一致する日記を取得
          required: true
          schema:
            type: string
            example: "猫"
        - in: query
          name: profile
          description: ユーザーのIDから、ユーザーが投稿した日記を取得
          required: true
          schema:
            type: integer
            example: 100
        - in: query
          name: liked_diaries
          description: ユーザーのIDから、ユーザーがいいねした日記を取得
          required: true
          schema:
            type: integer
            example: 100
        - in: query
          name: recent_diaries
          description: ユーザーのIDから、ユーザーが直近に投稿した日記の、猫の品種に基づくおすすめの日記を取得
          required: true
          schema:
            type: integer
            example: 100
        - in: query
          name: nearest_diaries
          description: ユーザーのIDから、ユーザーが直近に投稿した日記の、近所の日記を取得
          required: true
          schema:
            type: integer
            example: 100
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: 日記を作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                photo1: 
                  type: string
                  format: binary
                  description: image file
                photo2:
                  type: string
                  format: binary
                  description: image file
                photo3:
                  type: string
                  format: binary
                  description: image file
              required:
                - photo1
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/diaries/{pk}/:
    get:
      summary: 日記の詳細を取得
      parameters:
        - name: pk
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    put:
      summary: 日記を更新
      parameters:
        - name: pk
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                photo1: 
                  type: string
                  format: binary
                  description: image file
                photo2:
                  type: string
                  format: binary
                  description: image file
                photo3:
                  type: string
                  format: binary
                  description: image file
              required:
                - photo1
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    delete:
      summary: 日記を削除
      parameters:
        - name: pk
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/accounts/:
    get:
      summary: ユーザーリストを取得
      parameters:
        - in: path
          name: query
          description: 文字列にユーザ―名 or プロフィールが部分一致するユーザーを取得
          required: true
          schema:
            type: string
            example: "タロウ"
      response: 
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/follows/:
    get:
      summary: ユーザーのfollower、followingの取得
      parameters:
        - in: query
          name: followers
          description: ユーザーのID
          required: true
          schema:
            type: integer
            example: 100
        - in: query
          name: followings
          description: ユーザーのID
          required: true
          schema:
            type: integer
            example: 100
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: フォローする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                follower:
                  type: integer
                following:
                  type: integer
              required:
                - follower
                - following

  /api/inquiry/:
    post:
      summary: 問い合わせフォーム
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                title: 
                  type: string
                massage:
                  type: string
              required:
                - name
                - email
                - title
                - message
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
