version: '3.7'

services:
    # サービス名は自由に設定
    nyapu:
        # コンテナ名を明示的に指定
        container_name: nyapu
        build: ./
        # サービス起動後に入力されるコマンドを設定
        command: python /usr/src/app/nyapu/manage.py runserver 0.0.0.0:8000 --settings nyapu_pj.settings_dev
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./:/usr/src/app
        # 指定されたポートは接続されたサービスからアクセス可能
        ports:
            - 8000:8000
        # 環境変数を指定
        env_file: .env
        # 起動するサービスの依存関係を明記
        depends_on:
            - postgres
            - selenium

    postgres:
        # コンテナ名を明示的に指定
        container_name: postgres
        # 公式からイメージをpull
        image: postgres:10.17-alpine
        # データベースの永続化
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env.db

    selenium:
        # コンテナ名を明示的に指定
        container_name: selenium
        image: selenium/standalone-chrome:4.5.0-20221004
        ports:
         - 4444:4444
         - 5900:5900
        privileged: true
        shm_size: "2gb" 
        volumes:
            - /dev/shm:/dev/shm   

# トップレベルに書く「名前付きvolumes」は複数サービスから参照する
volumes:
    postgres_data: 

        
