version: '3.7'

services:
    # サービス名は自由に設定
    django:
        container_name: django
        build:
            context: django
            dockerfile: Dockerfile
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./django:/usr/src/app
        # 指定されたポートは接続されたサービスからアクセス可能
        ports:
            - 8000:8000
        # 環境変数を指定
        env_file: django/.env
        # 起動するサービスの依存関係を明記
        depends_on:
            - postgres
            - selenium

    vue:
        container_name: vue
        build:
            context: vue
            dockerfile: Dockerfile
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./vue:/usr/src/app
        # 指定されたポートは接続されたサービスからアクセス可能
        ports:
            - 8000:8000
        # 起動するサービスの依存関係を明記
        depends_on:
            - django

    postgres:
        container_name: postgres
        # 公式からイメージをpull
        image: postgres:13-alpine
        # データベースの永続化
        volumes:
            - postgres_data:/var/lib/postgresql/data
        # HeidiSQLの接続用にポート開放
        ports:
            - 5432:5432
        env_file: .env.db

    selenium:
        container_name: selenium
        image: selenium/standalone-chrome:4.5.0-20221004
        ports:
         - 4444:4444
         - 5900:5900
        privileged: true
        shm_size: "2gb" 
        volumes:
            - /dev/shm:/dev/shm   

# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    postgres_data: 

        
