# Generated by Django 4.0.2 on 2022-06-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_diary_lat_diary_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
                ('like_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_person', to=settings.AUTH_USER_MODEL, verbose_name='Likeした人')),
            ],
        ),
    ]
