# Generated by Django 4.0.2 on 2022-06-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
