# Generated by Django 4.0.2 on 2022-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='mapicon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='マップアイコン'),
        ),
    ]
