# Generated by Django 4.0.2 on 2022-07-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_mapicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='mapicon',
            field=models.ImageField(blank=True, null=True, upload_to='mapicon/', verbose_name='マップアイコン'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(upload_to='photo1/', verbose_name='写真１'),
        ),
    ]
