# Generated by Django 4.0.2 on 2022-09-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_alter_like_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
    ]
