# Generated by Django 3.2.14 on 2022-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_alter_diary_photo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(default="{% static 'assets/img/nyapu.png' %}", upload_to='', verbose_name='写真１'),
        ),
    ]
