# Generated by Django 3.2.14 on 2022-10-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20221012_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=35.709, max_digits=9, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=139.7319, max_digits=9, verbose_name='経度'),
        ),
    ]
