# Generated by Django 4.1.4 on 2023-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0023_alter_diary_created_at_alter_diary_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo1_most_similar_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='写真１で最も高い類似率'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='photo1_second_similar_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='写真１で2番目に高い類似率'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='photo1_third_similar_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='写真１で3番目に高い類似率'),
        ),
    ]
