# Generated by Django 4.1.4 on 2023-02-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0025_alter_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(default='static/assets/img/nyapu.png', upload_to='', verbose_name='写真１'),
        ),
    ]
