# Generated by Django 4.0.2 on 2022-06-18 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2200, null=True, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, max_length=2200, null=True, verbose_name='本文')),
                ('photo1', models.ImageField(upload_to='', verbose_name='写真１')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真２')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真３')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Diary',
            },
        ),
    ]
