# Generated by Django 4.0.2 on 2022-07-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
