# Generated by Django 4.0.2 on 2022-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=35.709, max_digits=9, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=139.7319, max_digits=9, verbose_name='経度'),
        ),
    ]
