# Generated by Django 4.0.2 on 2022-09-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_alter_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Like'},
        ),
    ]
