# Generated by Django 3.2.16 on 2022-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真１'),
        ),
    ]
