# Generated by Django 4.1.4 on 2023-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0021_alter_diary_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='photo1_most_similar_breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='写真１で最も類似した品種'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo1_most_similar_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='写真１で最も高い類似率'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo1_second_similar_breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='写真１で２番目に類似した品種'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo1_second_similar_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='写真１で2番目に高い類似率'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo1_third_similar_breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='写真１で３番目に類似した品種'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo1_third_similar_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='写真１で3番目に高い類似率'),
        ),
    ]
