# Generated by Django 4.1.4 on 2023-02-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0024_alter_diary_photo1_most_similar_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='タイトル'),
        ),
    ]
