# Generated by Django 4.1.4 on 2023-02-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0026_alter_diary_photo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(upload_to='', verbose_name='写真１'),
        ),
    ]
