# Generated by Django 4.0.2 on 2022-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_like_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.TextField(blank=True, max_length=472, null=True, verbose_name='自己紹介'),
        ),
    ]
