# Generated by Django 4.0.2 on 2022-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.TextField(blank=True, max_length=420, null=True, verbose_name='自己紹介'),
        ),
    ]
